# Generated by scripts/cli-release.mjs — do not edit by hand.
class M8t < Formula
  desc "CLI for managing m8t deployments on Azure / Microsoft Agent Foundry"
  homepage "https://github.com/m8t-labs/m8t"
  url "https://registry.npmjs.org/@m8t-stack/cli/-/cli-0.2.111.tgz"
  sha256 "4bf1ca7a53924bb4f107f85694c7178a2c26b4e42ccfcdc1d5c33f4aefddf5aa"
  license "MIT"
  version "0.2.111"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/m8t version")
  end
end
