# Generated by scripts/cli-release.mjs — do not edit by hand.
class M8t < Formula
  desc "CLI for managing m8t deployments on Azure / Microsoft Agent Foundry"
  homepage "https://github.com/m8t-labs/m8t"
  url "https://registry.npmjs.org/@m8t-stack/cli/-/cli-0.2.94.tgz"
  sha256 "5e04d91dd4e26e2b9eb4dbf4129126a8ee859607a26e041c04daf1f7272b81df"
  license "MIT"
  version "0.2.94"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/m8t version")
  end
end
