# Generated by scripts/cli-release.mjs — do not edit by hand.
class M8t < Formula
  desc "CLI for managing m8t deployments on Azure / Microsoft Agent Foundry"
  homepage "https://github.com/m8t-labs/m8t"
  url "https://registry.npmjs.org/@m8t-stack/cli/-/cli-0.2.129.tgz"
  sha256 "b5858bc5f2f298a02dff9e80ffd3b831d07f379d6c1265fb242bf39005e060ea"
  license "MIT"
  version "0.2.129"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/m8t version")
  end
end
